#!/bin/bash

for i in `seq 1 1 500`; do 
  echo brute_force.number_of_failed_logins_per_user.iyuvalk `iostat -c | grep -A1 'avg-cpu:' | tail -n1 | awk '{print $6}'` `date +%s` | nc localhost 3000
  sleep 1
done
